name: Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          REF=${GITHUB_REF##*/}
          echo ::set-env name=REF::${REF}
          echo ::set-env name=IMAGE::colomoto/colomoto-docker-base:${REF}
      - uses: actions/checkout@v2
      - run: docker build -t ${IMAGE} .
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        uses: actions-hub/docker@master
        with:
          args: push ${IMAGE}
      - name: Release info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
            docker run --rm ${IMAGE} apt list --installed > debian-installed.txt
            docker run --rm ${IMAGE} conda env export > conda-environment-strict.yml
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
            name: ${{ env.IMAGE }}
            files: |
                debian-installed.txt
                conda-environment-strict.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
