name: Announce release

on:
  push:
    tags:
        - '*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=GITHUB_TAG::$(echo $GITHUB_REF|cut -d/ -f3)
      - uses: actions/checkout@v2
      - name: release info
        run: |
            docker pull ${IMAGE_NAME}
            docker run --rm ${IMAGE_NAME} apt list --installed > debian-installed-${TAG}.txt
            docker run --rm ${IMAGE_NAME} conda env export > conda-environment-${TAG}-strict.yml
            docker run --rm ${IMAGE_NAME} conda env export --from-history > conda-environment-${TAG}.yml
        env:
            IMAGE_NAME: colomoto/colomoto-docker-base:${{ env.GITHUB_TAG }}
            TAG: ${{ env.GITHUB_TAG }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            name: colomoto/colomoto-docker-base:${{ env.GITHUB_TAG }}
            files: |
                debian-installed-${{ env.GITHUB_TAG }}
                conda-environment-${{ env.GITHUB_TAG }}-strict.yml
                conda-environment-${{ env.GITHUB_TAG }}.yml
